#
# Logging
#

CONFIG_ZMK_USB_LOGGING=n
CONFIG_ZMK_LOGGING_MINIMAL=y
CONFIG_PS2_LOG_LEVEL_DBG=n
CONFIG_UART_LOG_LEVEL_DBG=n
CONFIG_LOG_MODE_IMMEDIATE=n

# This setting is important to get the full log instead of
# one where the initial parts are cut out
CONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS=3000

CONFIG_ZMK_SLEEP=y
# Milliseconds of inactivity before entering idle state (turns off displays)
CONFIG_ZMK_IDLE_TIMEOUT=10000
# Milliseconds of inactivity before entering deep sleep (takes few seconds to reconnect bluetooth)
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=300000

CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_BATTERY_REPORTING=y
CONFIG_ZMK_WIDGET_BATTERY_STATUS=y
CONFIG_ZMK_WIDGET_OUTPUT_STATUS=y
CONFIG_ZMK_WIDGET_BATTERY_STATUS_SHOW_PERCENTAGE=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_ZMK_WIDGET_WPM_STATUS=n

CONFIG_NICE_PERI_VIEW_RIGHT_SIDE_CENTRAL=y